{% set name = "conda-mirror" %}
{% set version = "0.8.1.dev0" %}
{% set sha256 = "d297823742933e7f71581f9df86433f82d5faa7b16944e7bab14159f2a12459f" %}

{% set url_name = name.replace("-", "_") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  #url: https://pypi.io/packages/source/{{ url_name[0] }}/{{ url_name }}/{{ url_name }}-{{ version }}.tar.gz
  url: https://github.com/Quansight/conda-mirror/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - conda-mirror = conda_mirror.conda_mirror:cli

requirements:
  build:
    - python >=3.5
    - setuptools

  run:
    - python >=3.5
    - requests
    - pyyaml

test:
  imports:
    - conda_mirror

  commands:
    - conda-mirror --help

about:
  home: https://github.com/maxpoint/conda-mirror
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'mirror an upstream conda channel to a local directory'

extra:
  recipe-maintainers:
    - ericdill
    - parente
